"use client";

import { FormEvent, useEffect, useState } from "react";
import { configured, consumeAuthCallback, flushQueue, getSession, pendingCount, recordOrQueue, requestPasswordReset, rpc, select, signIn, signInChild, signOut, signUp, update, updatePassword } from "./lib/cloud";
import { privateAudioBlobUrl } from "./lib/cloud";
import { audioIdForArabic } from "./audioCatalog";
import AudioStudio from "./AudioStudio";
import NooraniCourse from "./NooraniCourse";

type Screen = "home" | "learn" | "practice" | "review" | "rewards" | "parent";
type Progress = {
  xp: number; coins: number; streak: number; completed: number[]; unlocked: number;
  correct: number; attempts: number; sessions: number; mistakes: Record<string, number>;
  owned: string[]; avatar: string; pin: string; lastPlayed: string;
};

const initial: Progress = { xp: 0, coins: 30, streak: 1, completed: [], unlocked: 0, correct: 0, attempts: 0, sessions: 0, mistakes: {}, owned: ["rookie"], avatar: "⚽", pin: "2468", lastPlayed: "" };
const letters = [
  ["ا","Alif"],["ب","Bā"],["ت","Tā"],["ث","Thā"],["ج","Jīm"],["ح","Ḥā"],["خ","Khā"],
  ["د","Dāl"],["ذ","Dhāl"],["ر","Rā"],["ز","Zā"],["س","Sīn"],["ش","Shīn"],["ص","Ṣād"],
  ["ض","Ḍād"],["ط","Ṭā"],["ظ","Ẓā"],["ع","ʿAyn"],["غ","Ghayn"],["ف","Fā"],["ق","Qāf"],
  ["ك","Kāf"],["ل","Lām"],["م","Mīm"],["ن","Nūn"],["ه","Hā"],["و","Wāw"],["ي","Yā"]
] as const;
const lessonGroups = ["ا ب ت ث","ج ح خ","د ذ","ر ز","س ش","ص ض","ط ظ","ع غ","ف ق","ك ل م ن ه و ي"];
const advanced = ["Similar letter families","Letter shapes","Fatḥah · َ","Kasrah · ِ","Ḍammah · ُ","Mixed short vowels","Join two letters","Join three letters","Sukoon · ْ","Tanween · ً ٍ ٌ","Shaddah · ّ","Long vowels · madd","Quranic word reading"];
const lessons = [...lessonGroups.map((arabic, i) => ({ title: `Letter Team ${i + 1}`, arabic, kind: "letters" })), ...advanced.map((title, i) => ({ title, arabic: ["بَ تَ ثَ","بِ تُ ثَ","مِنْ رَبِّ","قَالَ","رَبِّ"][Math.min(i,4)] || "بَ", kind: "skill" }))];
const games = [
  {id:"sound", icon:"🔊", name:"Sound Safari", blurb:"Listen and find the letter"},
  {id:"name", icon:"🔤", name:"Name Match", blurb:"Match letter to its name"},
  {id:"dots", icon:"🔎", name:"Dot Detective", blurb:"Spot the dot pattern"},
  {id:"build", icon:"🧱", name:"Word Builder", blurb:"Build an Arabic sound"},
  {id:"soccer", icon:"🥅", name:"Goalkeeper", blurb:"Save five penalty kicks"},
];
const shop = [
  {id:"star", icon:"⭐", name:"Star Striker", price:50}, {id:"lion", icon:"🦁", name:"Lion Captain", price:80},
  {id:"rocket", icon:"🚀", name:"Rocket Boots", price:110}, {id:"trophy", icon:"🏆", name:"Gold Cup", price:150},
];
function today(){ return new Date().toISOString().slice(0,10); }
function shuffle<T>(a:T[]){ return [...a].sort(()=>Math.random()-.5); }

type LearnerRow={id:string;display_name:string;avatar:string;current_lesson:number;daily_goal:number};
function AuthGate({onReady}:{onReady:(learner:LearnerRow,parent:boolean)=>void}){
  const [mode,setMode]=useState<"signin"|"signup"|"forgot"|"reset"|"child">("signin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [code,setCode]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  async function loadExisting(){const session=getSession();if(!session)return;try{if(session.user.is_anonymous){const rows=await select<LearnerRow[]>("learners","select=id,display_name,avatar,current_lesson,daily_goal&limit=1");if(rows[0])onReady(rows[0],false)}else{const id=await rpc<string>("create_family",{p_display_name:"Parent",p_learner_name:"Humza"});const rows=await select<LearnerRow[]>("learners",`select=id,display_name,avatar,current_lesson,daily_goal&id=eq.${id}`);if(rows[0])onReady(rows[0],true)}}catch(e){setError(e instanceof Error?e.message:"Unable to restore session")}}
  useEffect(()=>{if(!configured)return;void consumeAuthCallback().then(recovery=>recovery?setMode("reset"):loadExisting()).catch(e=>setError(e instanceof Error?e.message:"Unable to open reset link"))},[]);
  async function openParent(){const id=await rpc<string>("create_family",{p_display_name:"Parent",p_learner_name:"Humza"});const rows=await select<LearnerRow[]>("learners",`select=id,display_name,avatar,current_lesson,daily_goal&id=eq.${id}`);onReady(rows[0],true)}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{if(mode==="forgot"){await requestPasswordReset(email);setNotice("Reset email sent. Open it on this device, then choose a new password.");return}else if(mode==="reset"){await updatePassword(password);await openParent()}else if(mode==="signup"){const result=await signUp(email,password);if(!result.access_token){setNotice("Check your email to confirm the account, then sign in.");return}await openParent()}else if(mode==="signin"){await signIn(email,password);await openParent()}else{await signInChild();const learnerId=await rpc<string>("claim_child_device",{p_code:code});const rows=await select<LearnerRow[]>("learners",`select=id,display_name,avatar,current_lesson,daily_goal&id=eq.${learnerId}`);onReady(rows[0],false)}}catch(e){setError(e instanceof Error?e.message:"Unable to connect")}finally{setBusy(false)}}
  if(!configured)return <main className="auth-shell"><section className="auth-card"><span className="auth-mark">☪</span><h1>Connect Qaida Quest</h1><p>This build requires its Supabase project before it can safely save Humza’s progress. Add the two values from <code>.env.example</code>, run the database migration, then reopen the app.</p><div className="secure-note">🔒 No progress will be faked or stored as the authoritative copy on this device.</div></section></main>;
  return <main className="auth-shell"><section className="auth-card"><span className="auth-mark">☪</span><p className="eyebrow">HUMZA’S QAIDA QUEST</p><h1>{mode==="child"?"Connect this device":mode==="signup"?"Create parent account":mode==="forgot"?"Reset your password":mode==="reset"?"Choose a new password":"Welcome back"}</h1>{mode!=="reset"&&mode!=="forgot"&&<div className="auth-tabs"><button className={mode==="signin"?"active":""} onClick={()=>setMode("signin")}>Parent sign in</button><button className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Create account</button><button className={mode==="child"?"active":""} onClick={()=>setMode("child")}>Humza’s device</button></div>}<form onSubmit={submit}>{mode==="child"?<label>Six-digit code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} required/></label>:mode==="forgot"?<label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>:<>{mode!=="reset"&&<label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>}<label>{mode==="reset"?"New password":"Password"}<input type="password" minLength={8} autoComplete={mode==="signin"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} required/></label></>}<button className="primary wide" disabled={busy}>{busy?"Connecting…":mode==="child"?"Connect securely":mode==="signup"?"Create family account":mode==="forgot"?"Send reset email":mode==="reset"?"Save password & continue":"Sign in"}</button></form>{mode==="signin"&&<button className="text-button" onClick={()=>{setMode("forgot");setError("");setNotice("")}}>Forgot password?</button>}{(mode==="forgot"||mode==="reset")&&<button className="text-button" onClick={()=>setMode("signin")}>Back to sign in</button>}{error&&<p className="form-error">{error}</p>}{notice&&<p className="success">{notice}</p>}<small>{mode==="child"?"A parent creates this temporary code from the dashboard. It expires after 15 minutes.":"Your account protects Humza’s private learning data."}</small></section></main>;
}

export default function App(){const [learner,setLearner]=useState<LearnerRow|null>(null);const [parent,setParent]=useState(false);if(import.meta.env.DEV&&new URLSearchParams(location.search).has("course-preview"))return <NooraniCourse learnerId="preview" preview onClose={()=>location.assign("/")}/>;return learner?<Home learner={learner} parentMode={parent} onExit={async()=>{await signOut();setLearner(null)}}/>:<AuthGate onReady={(l,p)=>{setLearner(l);setParent(p)}}/>}

function Home({learner,parentMode,onExit}:{learner:LearnerRow;parentMode:boolean;onExit:()=>void}) {
  const [screen,setScreen]=useState<Screen>("home");
  const [p,setP]=useState<Progress>(initial);
  const [loaded,setLoaded]=useState(false);
  const [lesson,setLesson]=useState<number|null>(null);
  const [lessonStep,setLessonStep]=useState(0);
  const [game,setGame]=useState<string|null>(null);
  const [round,setRound]=useState(0);
  const [score,setScore]=useState(0);
  const [question,setQuestion]=useState(0);
  const [options,setOptions]=useState<number[]>([0,1,2,3]);
  const [feedback,setFeedback]=useState<"good"|"try"|null>(null);
  const [showInstall,setShowInstall]=useState(false);
  const [cloudState,setCloudState]=useState<"saved"|"saving"|"pending"|"error">("saving");
  const [pairingCode,setPairingCode]=useState("");
  const [showCourse,setShowCourse]=useState(false);

  useEffect(()=>{(async()=>{try{const [totals,progress,mastery,rewards]=await Promise.all([select<any[]>("learner_totals",`select=*&learner_id=eq.${learner.id}`),select<any[]>("lesson_progress",`select=*&learner_id=eq.${learner.id}`),select<any[]>("concept_mastery",`select=*&learner_id=eq.${learner.id}`),select<any[]>("rewards",`select=*&learner_id=eq.${learner.id}`)]);const t=totals[0];setP(v=>({...v,xp:t?.xp||0,coins:t?.coins??30,streak:t?.current_streak||0,sessions:t?.total_sessions||0,unlocked:learner.current_lesson,completed:progress.filter(x=>x.status==="complete").map(x=>Number(String(x.lesson_id).replace("lesson-",""))),mistakes:Object.fromEntries(mastery.map(x=>[x.concept_id,Number(x.review_priority)])),owned:["rookie",...rewards.map(x=>x.reward_id)],avatar:learner.avatar||"⚽"}));if(pendingCount()){const remaining=await flushQueue();setCloudState(remaining?"pending":"saved")}else setCloudState("saved")}catch{setCloudState("error")}finally{setLoaded(true)}})()},[learner.id]);
  useEffect(()=>{ if(import.meta.env.PROD&&"serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{}); },[]);
  const level=Math.floor(p.xp/100)+1;
  const accuracy=p.attempts?Math.round(p.correct/p.attempts*100):0;
  const currentLetter=letters[question%letters.length];

  async function playAudio(text:string){const itemId=audioIdForArabic(text);if(!itemId){setFeedback("try");return}try{const approved=await select<{storage_path:string}[]>("audio_recordings",`select=storage_path&learner_id=eq.${learner.id}&item_id=eq.${itemId}&status=eq.approved&order=version.desc&limit=1`);if(approved[0]){const objectUrl=await privateAudioBlobUrl(approved[0].storage_path),audio=new Audio(objectUrl);audio.onended=()=>URL.revokeObjectURL(objectUrl);await audio.play();return}await new Audio(`/audio/letters/${itemId}.wav`).play();setFeedback(null)}catch{try{await new Audio(`/audio/letters/${itemId}.wav`).play();setFeedback(null)}catch{setFeedback("try")}}}
  function startLesson(i:number){ if(i>p.unlocked)return; setLesson(i); setLessonStep(0); setFeedback(null); }
  async function finishLesson(){ if(lesson===null)return;const id=crypto.randomUUID(),now=new Date();setCloudState("saving");try{await recordOrQueue({p_id:id,p_learner_id:learner.id,p_type:"lesson",p_activity:`lesson-${lesson}`,p_started:new Date(now.getTime()-300000).toISOString(),p_ended:now.toISOString(),p_seconds:300,p_correct:3,p_total:3,p_xp:40,p_coins:15});setCloudState("saved")}catch{setCloudState("pending")}setP(v=>({...v,xp:v.xp+40,coins:v.coins+15,completed:[...new Set([...v.completed,lesson])],unlocked:Math.max(v.unlocked,Math.min(lessons.length-1,lesson+1)),lastPlayed:today()}));setLesson(null);setScreen("home");}
  function startGame(id:string, review=false){ const pool=review&&Object.keys(p.mistakes).length?letters.map((x,i)=>[i,p.mistakes[x[0]]||0] as const).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]):letters.map((_,i)=>i); const q=pool[Math.floor(Math.random()*pool.length)]; setQuestion(q); setOptions(shuffle([q,...shuffle(letters.map((_,i)=>i).filter(i=>i!==q)).slice(0,3)])); setGame(review?"review":id); setRound(0); setScore(0); setFeedback(null); }
  function answer(i:number){ if(feedback)return; const ok=i===question; setFeedback(ok?"good":"try"); setScore(s=>s+(ok?1:0)); setP(v=>({...v,correct:v.correct+(ok?1:0),attempts:v.attempts+1,mistakes:{...v.mistakes,[letters[question][0]]:Math.max(0,(v.mistakes[letters[question][0]]||0)+(ok?-1:2))}})); setTimeout(()=>{ if(round===4){const finalScore=score+(ok?1:0),xp=finalScore*5,coins=finalScore*2;setCloudState("saving");recordOrQueue({p_id:crypto.randomUUID(),p_learner_id:learner.id,p_type:game==="review"?"review":"game",p_activity:game||"practice",p_started:new Date(Date.now()-120000).toISOString(),p_ended:new Date().toISOString(),p_seconds:120,p_correct:finalScore,p_total:5,p_xp:xp,p_coins:coins}).then(()=>setCloudState("saved")).catch(()=>setCloudState("pending"));setP(v=>({...v,xp:v.xp+xp,coins:v.coins+coins,sessions:v.sessions+1,lastPlayed:today()}));setGame(null);setScreen("practice");}else{const next=Math.floor(Math.random()*letters.length);setQuestion(next);setOptions(shuffle([next,...shuffle(letters.map((_,n)=>n).filter(n=>n!==next)).slice(0,3)]));setRound(r=>r+1);setFeedback(null)}},700);}
  async function buy(id:string,price:number,icon:string){if(p.owned.includes(id)){setP(v=>({...v,avatar:icon}));return}try{setCloudState("saving");const result=await rpc<{coins:number}>("purchase_reward",{p_learner_id:learner.id,p_reward_id:id,p_cost:price});setP(v=>({...v,coins:result.coins,owned:[...v.owned,id],avatar:icon}));setCloudState("saved")}catch(e){alert(e instanceof Error?e.message:"Could not buy reward");setCloudState("error")}}
  async function createPairing(){try{const code=await rpc<string>("create_pairing_code",{p_learner_id:learner.id,p_device_name:"Humza iPad"});setPairingCode(code)}catch(e){alert(e instanceof Error?e.message:"Could not create code")}}
  async function unlockLesson(value:number){try{await update("learners",`id=eq.${learner.id}`,{current_lesson:value});setP(v=>({...v,unlocked:value}));setCloudState("saved")}catch{setCloudState("error")}}

  if(!loaded) return <main className="loading">Loading Humza’s quest…</main>;
  if(showCourse)return <NooraniCourse learnerId={learner.id} onClose={()=>setShowCourse(false)}/>;
  if(lesson!==null){ const l=lessons[lesson]; const group=l.arabic.split(" "); const target=group[lessonStep%group.length]; const steps=["Listen","Repeat","Recognize","Practice","Quick game","Complete"];
    return <main className="lesson-shell"><button className="close" onClick={()=>setLesson(null)}>✕</button><div className="lesson-progress"><span style={{width:`${(lessonStep+1)/6*100}%`}}/></div><div className="lesson-card"><span className="eyebrow">{steps[lessonStep]} · {lessonStep+1} of 6</span><h1>{lessonStep===0?"Listen carefully":lessonStep===1?"Now say it aloud":lessonStep===2?"Can you spot it?":lessonStep===3?"Tap the right letter":lessonStep===4?"One quick challenge!":"Lesson complete!"}</h1><div className="mega-arabic" dir="rtl">{lessonStep===5?"⭐":target}</div>{lessonStep<2&&<button className="audio-btn" onClick={()=>playAudio(target)}>▶ Human recording</button>}{lessonStep>=2&&lessonStep<5&&<div className="answer-grid">{shuffle(group).map((x,i)=><button key={i} className="arabic-choice" onClick={()=>setFeedback(x===target?"good":"try")}>{x}</button>)}</div>}{feedback&&lessonStep<5&&<p className={feedback==="good"?"success":"gentle"}>{feedback==="good"?"Brilliant! ⭐":"Recording unavailable or answer incorrect. Ask a grown-up to check the audio pack."}</p>}<button className="primary wide" disabled={lessonStep>=2&&lessonStep<5&&feedback!=="good"} onClick={()=>{setFeedback(null);lessonStep===5?finishLesson():setLessonStep(s=>s+1)}}>{lessonStep===5?"Save lesson & collect rewards":"Continue"} →</button>{lessonStep<2&&<small>Only teacher-supplied or licensed human recordings are used.</small>}</div></main>;
  }
  if(game){ const isSoccer=game==="soccer"; return <main className={`game-shell ${isSoccer?"pitch":""}`}><button className="close" onClick={()=>setGame(null)}>✕</button><div className="round-row"><b>{isSoccer?"Saves":"Score"}: {score}</b><span>{round+1} / 5</span></div><div className="game-card"><div className="game-mascot">{isSoccer?"🥅⚽":"🎯"}</div><span className="eyebrow">{game==="sound"?"Listen & choose":game==="review"?"Smart review":"Choose the match"}</span><h2>{game==="name"?`Find ${currentLetter[1]}`:game==="dots"?`Dot Detective says: find ${currentLetter[0]}`:game==="build"?`Build ${currentLetter[0]} · ${currentLetter[1]}`:isSoccer?`Save the shot from ${currentLetter[1]}!`:"Which letter is it?"}</h2>{game==="sound"&&<button className="audio-btn" onClick={()=>playAudio(currentLetter[0])}>▶ Play human recording</button>}<div className="answer-grid">{options.map(i=><button key={i} className={`arabic-choice ${feedback&&i===question?"right":""}`} onClick={()=>answer(i)}>{letters[i][0]}<small>{game==="name"?letters[i][1]:""}</small></button>)}</div>{feedback&&<p className={feedback==="good"?"success":"gentle"}>{feedback==="good"?(isSoccer?"Amazing save! 🧤":"Yes! Great work ⭐"):`That was ${currentLetter[0]} — keep going!`}</p>}</div></main>;
  }

  return <div className="app"><header><button className="brand" onClick={()=>setScreen("home")}><span>☪</span><b>Qaida Quest</b></button><div className="stats"><span className={`cloud ${cloudState}`}>{cloudState==="saved"?"☁ Saved":cloudState==="saving"?"☁ Saving…":cloudState==="pending"?`⇧ ${pendingCount()} pending`:"! Sync"}</span><span>🔥 {p.streak}</span><span>⭐ {p.xp}</span><span>🪙 {p.coins}</span><span className="avatar">{p.avatar}</span></div></header><main className="content">
    {screen==="home"&&<><section className="hero"><div><span className="eyebrow">YOUR DAILY QAIDA</span><h1>Assalamu Alaikum,<br/><em>Humza!</em></h1><p>Your real Noorani Qaida lesson is ready: a short portion, read aloud, with yesterday’s progress remembered.</p><button className="primary" onClick={()=>setShowCourse(true)}>Start today’s Qaida <span>→</span></button></div><div className="hero-art"><div className="sun">⭐</div><div className="hill"><div className="goal">📖</div><div className="kid">{p.avatar}</div><div className="ball">⚽</div></div></div></section><section className="today"><div className="section-title"><div><span className="eyebrow">THE TAQWA METHOD</span><h2>Listen. Point. Repeat. Read.</h2></div><b>10 min</b></div><div className="mission-row"><div className="mission done"><i>¼</i><span><b>Small portion</b><small>Quarters before halves</small></span></div><div className="mission"><i>🔊</i><span><b>Read aloud</b><small>Sound before speed</small></span></div><div className="mission"><i>↻</i><span><b>Review</b><small>Repeat until secure</small></span></div></div></section><section className="level-card"><span className="level-badge">{level}</span><div><b>Level {level} · Rising Reader</b><div className="bar"><span style={{width:`${p.xp%100}%`}}/></div><small>{p.xp%100} / 100 XP to next level</small></div><span>🏆</span></section><button className="install-tip" onClick={()=>setShowInstall(!showInstall)}>📲 {showInstall?"In Safari: tap Share, then Add to Home Screen.":"Put Qaida Quest on Humza’s iPad"}</button></>}
    {screen==="learn"&&<><div className="page-head"><span className="eyebrow">COMPLETE 33-PAGE COURSE</span><h1>Noorani Qaida</h1><p>Follow the real book from alphabet recognition through combined reading rules.</p><button className="primary" onClick={()=>setShowCourse(true)}>Open today’s assigned portion →</button></div><div className="method-stages">{["Letters and joined shapes","Short vowels and tanween","Madd, sukoon and tashdeed","Combined reading practice"].map((title,i)=><article key={title}><span>{i+1}</span><div><b>{title}</b><small>{["Pages 2–6","Pages 7–12","Pages 13–29","Pages 30–33"][i]}</small></div></article>)}</div></>}
    {screen==="practice"&&<><div className="page-head"><span className="eyebrow">5-QUESTION ROUNDS</span><h1>Practice Playground</h1><p>Pick a game. Every round earns XP and coins.</p></div><div className="game-grid">{games.map(g=><button className="game-tile" key={g.id} onClick={()=>startGame(g.id)}><span>{g.icon}</span><div><b>{g.name}</b><small>{g.blurb}</small></div><i>Play →</i></button>)}</div></>}
    {screen==="review"&&<><div className="page-head"><span className="eyebrow">SMART PRACTICE</span><h1>Mistake Busters</h1><p>Qaida Quest remembers tricky letters and brings them back gently.</p></div><section className="review-card"><div className="review-art">🛡️</div><div><h2>{Object.values(p.mistakes).some(x=>x>0)?"Your review is ready!":"Nothing tricky yet!"}</h2><p>{Object.values(p.mistakes).some(x=>x>0)?"A quick round focused on the letters that need a little more practice.":"Play a practice game and we’ll build a smart review for you."}</p><div className="tricky">{Object.entries(p.mistakes).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k])=><span key={k}>{k}</span>)}</div><button className="primary" onClick={()=>startGame("review",true)}>Start quick review →</button></div></section></>}
    {screen==="rewards"&&<><div className="page-head"><span className="eyebrow">YOUR CLUBHOUSE</span><h1>Rewards</h1><p>Spend learning coins. No real money—ever.</p></div><section className="trophy-row"><div><span>🏅</span><b>First Steps</b><small>{p.completed.length?"Earned":"Complete a lesson"}</small></div><div><span>🔥</span><b>On Fire</b><small>{p.streak>=3?"Earned":"Reach a 3-day streak"}</small></div><div><span>⚽</span><b>Safe Hands</b><small>{p.sessions>=3?"Earned":"Play 3 rounds"}</small></div></section><div className="shop-head"><h2>Reward shop</h2><span>🪙 {p.coins} coins</span></div><div className="shop-grid">{shop.map(x=><button key={x.id} className={`shop-item ${p.owned.includes(x.id)?"owned":""}`} onClick={()=>buy(x.id,x.price,x.icon)}><span>{x.icon}</span><b>{x.name}</b><small>{p.owned.includes(x.id)?(p.avatar===x.icon?"Equipped":"Tap to equip"):`🪙 ${x.price}`}</small></button>)}</div></>}
    {screen==="parent"&&parentMode&&<><div className="page-head"><span className="eyebrow">SECURE PARENT DASHBOARD</span><h1>{learner.display_name}’s progress</h1><p>Live cloud totals available from any signed-in device.</p></div><div className="parent-stats"><div><b>{p.completed.length}</b><small>Lessons complete</small></div><div><b>{accuracy}%</b><small>Accuracy</small></div><div><b>{p.sessions}</b><small>Practice rounds</small></div><div><b>{p.streak}</b><small>Day streak</small></div></div><section className="parent-panel"><h2>Learning snapshot</h2><p><b>Current lesson:</b> {lessons[p.unlocked]?.title}</p><p><b>Needs review:</b> {Object.entries(p.mistakes).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k])=>k).join(" · ")||"No patterns yet"}</p><label>Unlock through lesson <select value={p.unlocked} onChange={e=>unlockLesson(Number(e.target.value))}>{lessons.map((l,i)=><option key={i} value={i}>{i+1}. {l.title}</option>)}</select></label><div className="pair-box"><h3>Connect Humza’s iPad</h3><p>Create a one-time code, then choose “Humza’s device” on the iPad. Codes expire in 15 minutes.</p>{pairingCode?<strong>{pairingCode}</strong>:<button className="primary" onClick={createPairing}>Create device code</button>}</div><button className="danger" onClick={onExit}>Sign out</button></section><AudioStudio learnerId={learner.id}/></>}
  </main><nav>{(["home","learn","practice","review","rewards",...(parentMode?["parent" as Screen]:[])] as Screen[]).map((x,i)=><button key={x} className={screen===x?"active":""} onClick={()=>setScreen(x)}><span>{["⌂","🗺️","⚽","↻","🏆","⚙"][i]}</span>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav></div>;
}
