import { useEffect, useRef, useState } from "react";
import { audioCatalog } from "./audioCatalog";
import { insert, privateAudioUrl, select, update, uploadPrivateAudio } from "./lib/cloud";

type Recording={id:string;item_id:string;storage_path:string;version:number;status:"draft"|"in_review"|"approved"|"rejected";speaker_name:string;reviewer_name:string|null;created_at:string;notes:string|null};

const SOURCE_URL="https://commons.wikimedia.org/wiki/File:Arabic_alphabets.ogg";
const SOURCE_LICENSE="CC BY-SA 4.0";
const SOURCE_ATTRIBUTION='“Arabic alphabets” by Atef1975, divided into individual letter-name clips; changes were made.';

export default function AudioStudio({learnerId}:{learnerId:string}){
  const [item,setItem]=useState("letter_alif"),[rows,setRows]=useState<Recording[]>([]),[speaker,setSpeaker]=useState(""),[reviewer,setReviewer]=useState(""),[permission,setPermission]=useState(false),[file,setFile]=useState<Blob|null>(null),[busy,setBusy]=useState(false),[publishing,setPublishing]=useState<string|null>(null),[message,setMessage]=useState("");
  const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);
  async function load(){setRows(await select<Recording[]>("audio_recordings",`select=*&learner_id=eq.${learnerId}&order=created_at.desc`))}
  useEffect(()=>{void load()},[learnerId]);
  async function start(){setMessage("");if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setMessage("Recording is not supported here. Use Choose audio file instead.");return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{setFile(new Blob(chunks.current,{type:r.mimeType||"audio/webm"}));stream.getTracks().forEach(t=>t.stop());setMessage("Recording captured. Listen, then upload for review.")};r.start();setMessage("Recording…")}
  function stop(){recorder.current?.stop()}
  async function preview(blob=file){if(!blob)return;const u=URL.createObjectURL(blob);const a=new Audio(u);a.onended=()=>URL.revokeObjectURL(u);await a.play()}
  async function upload(){if(!file||!speaker.trim()||!permission){setMessage("Add a speaker name, permission confirmation, and recording first.");return}setBusy(true);setMessage("");try{const ext=file.type.includes("mp4")?"m4a":file.type.includes("mpeg")?"mp3":"webm";const path=`${learnerId}/${item}/${crypto.randomUUID()}.${ext}`;await uploadPrivateAudio(path,file);await insert("audio_recordings",{learner_id:learnerId,item_id:item,storage_path:path,status:"in_review",speaker_name:speaker.trim(),permission_confirmed:true,source_kind:"teacher_recording",mime_type:file.type||"audio/webm"});setFile(null);setMessage("Uploaded privately. It is not available to Humza until approved.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
  async function review(row:Recording,status:"approved"|"rejected"){if(!reviewer.trim()){setMessage("Enter the reviewer’s name first.");return}try{await update("audio_recordings",`id=eq.${row.id}`,{status,reviewer_name:reviewer.trim(),reviewed_at:new Date().toISOString()});setMessage(status==="approved"?"Approved. This version is now available to Humza.":"Rejected. Humza cannot play this version.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Review could not be saved")}}
  async function play(row:Recording){try{await new Audio(await privateAudioUrl(row.storage_path)).play()}catch(e){setMessage(e instanceof Error?e.message:"Could not play recording")}}
  async function publishSource(audioId:string){
    if(!reviewer.trim()){setMessage("Enter the teacher or reviewer’s name before approving a sourced clip.");return}
    setPublishing(audioId);setMessage("");
    try{
      const response=await fetch(`/audio/letters/${audioId}.wav`);if(!response.ok)throw new Error("Source clip is missing from this deployment.");
      const blob=await response.blob(),path=`${learnerId}/${audioId}/wikimedia-atef1975-${crypto.randomUUID()}.wav`;
      await uploadPrivateAudio(path,new Blob([blob],{type:"audio/wav"}));
      await insert("audio_recordings",{learner_id:learnerId,item_id:audioId,storage_path:path,status:"approved",speaker_name:"Atef1975",reviewer_name:reviewer.trim(),reviewed_at:new Date().toISOString(),permission_confirmed:true,source_kind:"licensed_derivative",mime_type:"audio/wav",source_url:SOURCE_URL,source_license:SOURCE_LICENSE,source_attribution:SOURCE_ATTRIBUTION,notes:"Letter-name clip split from the verified source recording; reviewed before publication."});
      setMessage("Approved and published. Humza can play this letter now.");await load();
    }catch(e){setMessage(e instanceof Error?e.message:"Could not publish this clip")}finally{setPublishing(null)}
  }
  const chosen=audioCatalog.find(x=>x[0]===item)!;
  const approved=new Set(rows.filter(r=>r.status==="approved").map(r=>r.item_id));
  return <section className="audio-studio"><span className="eyebrow">TEACHER AUDIO STUDIO</span><h2>Review the real voice pack</h2><p>Listen to each licensed human recording. A named teacher or grown-up must approve the exact clip before Humza hears it in lessons.</p><label>Teacher / reviewer name<input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Name of person checking pronunciation"/></label>{message&&<p className="studio-message" role="status">{message}</p>}<div className="recording-list source-review">{audioCatalog.map(([id,arabic,label])=><article key={id}><div><b dir="rtl">{arabic} <span dir="ltr">{label}</span></b><small>{approved.has(id)?"approved and live":"Atef1975 · CC BY-SA 4.0 · needs review"}</small></div><button onClick={()=>void new Audio(`/audio/letters/${id}.wav`).play()}>▶ Listen</button>{!approved.has(id)&&<button disabled={publishing!==null} onClick={()=>publishSource(id)}>{publishing===id?"Publishing…":"Approve & publish"}</button>}</article>)}</div><hr/><h2>Record a teacher replacement</h2><div className="studio-grid"><label>Sound<select value={item} onChange={e=>setItem(e.target.value)}>{audioCatalog.map(x=><option key={x[0]} value={x[0]}>{x[1]} — {x[2]}</option>)}</select></label><label>Speaker<input value={speaker} onChange={e=>setSpeaker(e.target.value)} placeholder="Teacher’s name"/></label></div><div className="record-card"><strong dir="rtl">{chosen[1]}</strong><div><button onClick={start}>● Record</button><button onClick={stop}>■ Stop</button><label className="file-button">Choose audio file<input type="file" accept="audio/*" capture="user" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<button onClick={()=>preview()}>▶ Listen</button>}</div></div><label className="permission"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/> I have the speaker’s permission to store and use this recording for Humza’s lessons.</label><button className="primary" disabled={busy||!file} onClick={upload}>{busy?"Uploading…":"Upload for review"}</button><div className="recording-list">{rows.map(r=><article key={r.id}><div><b>{audioCatalog.find(x=>x[0]===r.item_id)?.[1]} {audioCatalog.find(x=>x[0]===r.item_id)?.[2]}</b><small>v{r.version} · {r.status.replace("_"," ")} · {r.speaker_name}</small></div><button onClick={()=>play(r)}>▶</button>{r.status!=="approved"&&<button onClick={()=>review(r,"approved")}>Approve</button>}{r.status!=="rejected"&&<button onClick={()=>review(r,"rejected")}>Reject</button>}</article>)}</div><details><summary>Audio credits and licensing</summary><p>“Arabic alphabets” by Atef1975, <a href={SOURCE_URL}>Wikimedia Commons</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>. The original was divided into individual clips and normalized; changes were made. No endorsement is implied. See <a href="/AUDIO-LICENSES.md">AUDIO-LICENSES.md</a>.</p></details></section>
}
