import { useEffect, useRef, useState } from "react";
import { audioCatalog } from "./audioCatalog";
import { insert, privateAudioUrl, select, update, uploadPrivateAudio } from "./lib/cloud";

type Recording={id:string;item_id:string;storage_path:string;version:number;status:"draft"|"in_review"|"approved"|"rejected";speaker_name:string;reviewer_name:string|null;created_at:string;notes:string|null};

export default function AudioStudio({learnerId}:{learnerId:string}){
  const [item,setItem]=useState("letter_alif"),[rows,setRows]=useState<Recording[]>([]),[speaker,setSpeaker]=useState(""),[reviewer,setReviewer]=useState(""),[permission,setPermission]=useState(false),[file,setFile]=useState<Blob|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);
  async function load(){setRows(await select<Recording[]>("audio_recordings",`select=*&learner_id=eq.${learnerId}&order=created_at.desc`))}
  useEffect(()=>{void load()},[learnerId]);
  async function start(){setMessage("");if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setMessage("Recording is not supported here. Use Choose audio file instead.");return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{setFile(new Blob(chunks.current,{type:r.mimeType||"audio/webm"}));stream.getTracks().forEach(t=>t.stop());setMessage("Recording captured. Listen, then upload for review.")};r.start();setMessage("Recording…")}
  function stop(){recorder.current?.stop()}
  async function preview(blob=file){if(!blob)return;const u=URL.createObjectURL(blob);const a=new Audio(u);a.onended=()=>URL.revokeObjectURL(u);await a.play()}
  async function upload(){if(!file||!speaker.trim()||!permission){setMessage("Add a speaker name, permission confirmation, and recording first.");return}setBusy(true);setMessage("");try{const ext=file.type.includes("mp4")?"m4a":file.type.includes("mpeg")?"mp3":"webm";const path=`${learnerId}/${item}/${crypto.randomUUID()}.${ext}`;await uploadPrivateAudio(path,file);await insert("audio_recordings",{learner_id:learnerId,item_id:item,storage_path:path,status:"in_review",speaker_name:speaker.trim(),permission_confirmed:true,source_kind:"teacher_recording",mime_type:file.type||"audio/webm"});setFile(null);setMessage("Uploaded privately. It is not available to Humza until approved.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
  async function review(row:Recording,status:"approved"|"rejected"){if(!reviewer.trim()){setMessage("Enter the reviewer’s name first.");return}await update("audio_recordings",`id=eq.${row.id}`,{status,reviewer_name:reviewer.trim(),reviewed_at:new Date().toISOString()});setMessage(status==="approved"?"Approved. This version is now available to Humza.":"Rejected. Humza cannot play this version.");await load()}
  async function play(row:Recording){try{new Audio(await privateAudioUrl(row.storage_path)).play()}catch(e){setMessage(e instanceof Error?e.message:"Could not play recording")}}
  const chosen=audioCatalog.find(x=>x[0]===item)!;
  return <section className="audio-studio"><span className="eyebrow">TEACHER AUDIO STUDIO</span><h2>Record, review, then approve</h2><p>Nothing reaches Humza until a named reviewer approves that exact version.</p><div className="studio-grid"><label>Sound<select value={item} onChange={e=>setItem(e.target.value)}>{audioCatalog.map(x=><option key={x[0]} value={x[0]}>{x[1]} — {x[2]}</option>)}</select></label><label>Speaker<input value={speaker} onChange={e=>setSpeaker(e.target.value)} placeholder="Teacher’s name"/></label><label>Reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Reviewer’s name"/></label></div><div className="record-card"><strong dir="rtl">{chosen[1]}</strong><div><button onClick={start}>● Record</button><button onClick={stop}>■ Stop</button><label className="file-button">Choose audio file<input type="file" accept="audio/*" capture="user" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<button onClick={()=>preview()}>▶ Listen</button>}</div></div><label className="permission"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/> I have the speaker’s permission to store and use this recording for Humza’s lessons.</label><button className="primary" disabled={busy||!file} onClick={upload}>{busy?"Uploading…":"Upload for review"}</button>{message&&<p className="studio-message" role="status">{message}</p>}<div className="recording-list">{rows.length===0?<p>No teacher recordings yet.</p>:rows.map(r=><article key={r.id}><div><b>{audioCatalog.find(x=>x[0]===r.item_id)?.[1]} {audioCatalog.find(x=>x[0]===r.item_id)?.[2]}</b><small>v{r.version} · {r.status.replace("_"," ")} · {r.speaker_name}</small></div><button onClick={()=>play(r)}>▶</button>{r.status!=="approved"&&<button onClick={()=>review(r,"approved")}>Approve</button>}{r.status!=="rejected"&&<button onClick={()=>review(r,"rejected")}>Reject</button>}</article>)}</div><details><summary>Audio credits and licensing</summary><p>Wikimedia candidate: “Arabic alphabets.ogg” by Atef1975, CC BY-SA 4.0. Any split or cleaned clips are adaptations and must keep attribution and ShareAlike terms. Teacher recordings require recorded permission. See <a href="/AUDIO-LICENSES.md">AUDIO-LICENSES.md</a>.</p></details></section>
}
